package org.example.vladtech.reviews.mapperlayer;

import org.example.vladtech.reviews.data.Review;
import org.example.vladtech.reviews.presentation.ReviewRequestModel;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface ReviewRequestMapper {
    // Map from request DTO → entity
    // Ignore ID if it's generated by the database
    @Mapping(target = "reviewId", ignore = true)
    @Mapping(target = "photos", ignore = true)
    @Mapping(target = "clientName", ignore = true)
    @Mapping(target = "ownerAuth0Id", ignore = true)
    Review requestModelToEntity(ReviewRequestModel reviewRequestModel);
}
